### ISSUE TITLE
Some downloads fail with ZipException

### ISSUE THREAD

**Issue by 0x7d7b** [stevespringett/nist-data-mirror#49]
After starting the nist-data-mirror Docker container (`docker run -it --rm -p 80:80 sspringett/nvdmirror`), several file downloads fail with the following error message:
```
2019-10-18 19:50:12,011 INFO success: initialize_htdocs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at us.springett.nistdatamirror.NistDataMirror.uncompress(NistDataMirror.java:225)
	at us.springett.nistdatamirror.NistDataMirror.doDownload(NistDataMirror.java:214)
	at us.springett.nistdatamirror.NistDataMirror.mirror(NistDataMirror.java:128)
	at us.springett.nistdatamirror.NistDataMirror.main(NistDataMirror.java:70)
```

**Comment by 0x7d7b** [comment]
See also https://github.com/stevespringett/nist-data-mirror/pull/43#issuecomment-543907497 .

**Comment by 0x7d7b** [comment]
It seems that this has been fixed with one of the latest master branch builds.
